highlighter: rouge
# Site settings
title: ret.re - reverse and more
email: vhs@ret.re
description: "I'm a security professional in vulnerability management and also security testing. This website is an attempt to expose what I do on non-labour hours and I hope motivate others to follow this awesome IT field."
baseurl: ""
url: "https://ret.re"
twitter_username: pushdword
github_username:  pushdword

# Build settings
markdown: kramdown
